name: Pre-Commit

on:
  push:
    branches:
      - main

env:
  TF_PLUGIN_CACHE_DIR: ${{ github.workspace }}/.terraform.d/plugin-cache

jobs:
  pre-commit:
    name: Pre-commit validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Setup Python environment
        uses: actions/setup-python@v2
      - name: Setup Terraform Cache
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-${{ hashFiles('**/.terraform.lock.hcl') }}
          path: ${{ env.TF_PLUGIN_CACHE_DIR }}
      - name: Setup Go environment
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: "Install pre-commit tools: terraform-docs, tflint & tfsec"
        run: |
          mkdir -p $TF_PLUGIN_CACHE_DIR
          go install github.com/terraform-docs/terraform-docs@latest
          sudo mv $(go env GOPATH)/bin/terraform-docs /usr/local/bin/terraform-docs
          curl -sSLf "$(curl -sS https://api.github.com/repos/terraform-linters/tflint/releases/latest | grep -o -E "https://.+?_linux_amd64.zip")" > tflint.zip
          unzip tflint.zip && rm tflint.zip
          sudo mv tflint /usr/local/bin/
          go install github.com/aquasecurity/tfsec/cmd/tfsec@latest
          sudo mv $(go env GOPATH)/bin/tfsec /usr/local/bin/tfsec
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.10
      - name: Run pre-commit hooks
        uses: pre-commit/action@v2.0.0
        env:
          GO111MODULE: auto
