name: Mark or close stale Issues & PRs
on:
  schedule:
    # Scheduled workflows run on the latest commit on the default or base branch
    # every day at 3am UTC
    - cron: '0 3 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      actions: none
      checks: none
      contents: none
      deployments: none
      id-token: none
      issues: write
      packages: none
      pages: none
      pull-requests: write
      repository-projects: none
      security-events: none
      statuses: none
    steps:
      - name: "Close Stale Issues & PRs 🔇"
        # This Github Action [https://github.com/marketplace/actions/close-stale-issues] is verified by GitHub and has the label "Verified creator". That's why we are using the final tag directly.
        uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          # Staling issues and PR's
          days-before-stale: 30
          stale-issue-label: stale
          stale-pr-label: stale
          stale-issue-message: |
            This issue has been automatically marked as stale because it has been open 30 days
            with no activity. Remove stale label or comment or this issue will be closed in 10 days
          stale-pr-message: |
            This PR has been automatically marked as stale because it has been open 30 days
            with no activity. Remove stale label or comment or this PR will be closed in 10 days
          # Not stale if have this labels or part of milestone
          exempt-issue-labels: bug,wip,on-hold
          exempt-pr-labels: bug,wip,on-hold
          exempt-all-milestones: true
          # Close issue operations
          # Label will be automatically removed if the issues are no longer closed nor locked.
          days-before-close: 10
          delete-branch: true
          close-issue-message: This issue was automatically closed because of stale in 10 days
          close-pr-message: This PR was automatically closed because of stale in 10 days
